openapi: 3.0.3
info:
  title: Sistema de Gestión Bancaria
  description: API para manejar información de clientes, cuentas bancarias, créditos y transacciones.
  version: 1.0.0
tags:
  - name: customers
    description: All about your customer information
    externalDocs:
      description: Find out more
      url: http://swagger.
servers:
  - url: http://localhost:8080/api/v1
paths:
  /customers:
    get:
      tags:
        - customers
      summary: Get list of all clients
      responses:
        '200':
          description: Client List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerResponse'
        '500':
          description: Server error 
    post:
      tags:
        - customers
      summary: Create a new client
      requestBody:
        description: Data to create the client
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '201':
          description: Client created
            
    
  /customers/{id}:
    get:
      tags:
        - customers
      summary: Get a customer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Client found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '404':
          description: Client not found
    put:
      tags:
        - customers
      summary: Actualizar un cliente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Datos para actualizar el cliente
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '200':
          description: Updated client
          
        '404':
          description: Client not found  
          
    delete:
      tags:
        - customers
      summary: Delete a customer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted customer   
               
                  
components:
  schemas:
    CustomerResponse:
      type: object
      properties:
        id:
          type: string
          description: unique client id
        clientType:
          type: string
          enum: [business, staff]
          description: Client type
        documentType:
          type: string
          enum: [DNI, CE]
          description: Document type  
        documentNumber:
          type: string
          description: Document number
        name:
          type: string
          description: Names
        lastName:
          type: string
          description: surnames  
        email:
          type: string
          description: Customer emeal
          
    CustomerRequest:
      type: object
      properties:
        clientType:
          type: string
          enum: [business, staff]
          description: Client type
        documentType:
          type: string
          enum: [DNI, CE]
          description: Document type  
        documentNumber:
          type: string
          description: Document number
        name:
          type: string
          description: Names
        lastName:
          type: string
          description: surnames  
        email:
          type: string
          description: Customer emeal        
          