openapi: 3.0.3
info:
  title: Sistema de Gestión Bancaria
  description: API para manejar información de clientes, cuentas bancarias, créditos y transacciones.
  version: 1.0.0
tags:
  - name: customers
    description: All about your customer information
    externalDocs:
      description: Find out more
      url: http://swagger.
servers:
  - url: http://localhost:8080/api/v1
paths:
  /customers:
    get:
      tags:
        - customers
      summary: Get list of all clients
      responses:
        '200':
          description: Client List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '500':
          description: Server error          
                  
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
          description: unique client id
        clientType:
          type: string
          enum: [business, staff]
          description: Client type
        name:
          type: string
          description: Customer name      
          